### ISSUE TITLE
Improve / implement a UI to switch between inputs once in VR mode.

### ISSUE THREAD

**Issue by borismus** [borismus/webvr-boilerplate#11]
I think we need a UI in the boilerplate to pick between VRDevices. Related: https://github.com/borismus/webvr-polyfill/issues/4

**Comment by jtgi** [comment]
I took a stroll through the code with this issue in mind.

Just to clarify, the idea is to enable a user to switch between all supported inputs (mouse/kb, touch, hmd) including when they have multiple hmds connected, right?

Some food for thought on the UX/Design side:
1. When should an input menu be displayed?
   - if no hmd (ex: keyboard/touch), don't display any menu; enter immersive on any action.
   - if 1 hmd and canvas selected, take user straight into VR.
   - if 1 hmd and WebVRButton selected open input select menu
   - if N hmds and WebVRButton selected display menu.
   - if N hmds and canvas selected... display flyout menu?
   - Have a separate button entirely for selecting inputs.
2. Should a user be able to switch inputs once in VR? 
   - I'd say probably not. User can only exit Immersive/VR mode. Inputs are only selected via touch or mouse/keyboard.

Basic work items seem something like: 
1. Detect and return multiple hmds.
   - Requires updating VREffect and a fair amount of WebVRManager.
2. Implement an input select menu (showing/hiding/animating/etc).
3. Launch Immersive or VR Mode based on input selected.
4. Bake in some sane defaults to avoid showing an input menu unless we must. ^ Design dependent.

If this issue is still of interest, any thoughts?

**Comment by borismus** [comment]
John, thanks for your interest :)

Overall, yes the issue is disambiguating between HMDs and inputs. However I think the general problem is really hard, and I'd like to tackle a real world issue first: disambiguating between different types of Cardboard-like viewers. This situation is especially tricky since Cardboard-style VR doesn't have any way to convey data about the optical params of the HMD.

So I think there are a couple of possibilities: either we enumerate the top N popular Cardboard-like devices (eg. durovis dive, etc), and/or we do what [WWGC](https://github.com/google/wwgc) does, and support scanning of QR codes to pick the right device params which are encoded therein.

I do think that it may be worthwhile to actually allow switching Cardboard params within VR mode. In VR mode, there could be a little configuration gear (similar to native Cardboard app) that you tap to reveal a UI to scan a QR code or pick a popular device. Outside of VR mode I think it's a lot to ask users to specify which configuration they prefer to use.

A big problem is that this config can be persisted per-domain only, unless we want users to login to get their preferred Cardboard-like device params :\

So more specifically, I think implementing this in-VR UI and QR scanner would be an excellent start.

**Comment by borismus** [comment]
Currently have a UI for picking viewer profile which works on both iOS and Android. Eventually aiming for a QR picker.

**Comment by PixelPartner** [comment]
The URLs encoded in the official WWGC QRCodes do not directly encode the parameters, but are shortURL links hosted by Google redircting to the real (much longer) ones. This way they can also chop of functionality of cardboard viewers they don't like any longer. i.e the ones using head straps - my favs.
