### ISSUE TITLE
Set initial camera orientation?

### ISSUE THREAD

**Issue by Mikebest3d** [borismus/webvr-boilerplate#116]
With a basic setup, it is possible to adjust the camera's starting position, but not the initial orientation:

var controls = new THREE.VRControls(camera);

camera.position.set(0.0,1.5,0.3) ; // works fine

camera.rotation.x = -0.3 ; // has no effect as the orientation is directly piped from VR controls...

Would it be possible to somehow set in initial camera or controls orientation? It would be useful -  particularly in non-vr mode  - for framing the initial shot before the VR controls kick-in and point everything down z...  

I tried dropping the camera into a group, then doing this..

var controls = new THREE.VRControls(group);  // allows me to set the intial orientation, but controls break.. 

Any ideas on how best achieve this? thanks

**Comment by borismus** [comment]
This is a three.js question, not webvr-boilerplate. Sorry, closing.

**Comment by brianchirls** [comment]
@Mikebest3d:
You don't want to mess with the camera position or rotation at all because it'll get clobbered by the VR controls. What I do is make a `THREE.Object3D` called `body` and add the camera as a child of that object. Then you can move or rotate `body` wherever you want. Sometimes I'll set the `y` of `body` to around 1.5 meters, in the general range of a person's average height.

@borismus:
Given that the problem of VR controls overwriting the camera pose and the solution are VR specific, I'd argue it is a webvr question, not a three.js one. It may not be a bad idea to implement this set up as part of the boilerplate.

**Comment by Mikebest3d** [comment]
@brianchirls Thanks Brian.  I had actually tried that before, but realize I forgot to put the parent object into the scene (schoolboy error).   Its working fine now.. :)

EDIT: actually, maybe not so much.  It works.. but there is an issue, which is quite VR specific. Putting the camera into a rig gives me the initial orientation I was after.  I can point the camera at what I want to start out - say looking down 45 degrees.  But then when I tilt my head back up to 0 degrees, and then pan around the room - the camera pans based on the original parent's 45 degree angle.  Yuck..definitely not what is expected.   

Not sure if this is so much a webvr thing or a three thing, or just a 'VR can be a bit of a pain' thing...

**Comment by borismus** [comment]
Fair enough @brian, but it's really a VRControls issue, which is part of
THREE.
