### ISSUE TITLE
Touch control axes are switched in mobile Firefox

### ISSUE THREAD

**Issue by brianchirls** [borismus/webvr-boilerplate#63]
Move your fingers left/right, and the camera looks up/down.

**Comment by borismus** [comment]
This is only happening in landscape mode. cc @caseyyee

**Comment by caseyyee** [comment]
This is due to Firefox not returning proper `window.orientation`.   This has been fixed in the Nightly versions of Firefox Android, but will take some time to trickle down to beta and stable versions.

To fix this, you can detect orientation (though only in one direction) by checking the media orientation:

`var landscapeOrientation = window.matchMedia("(orientation: landscape)")`

**Comment by borismus** [comment]
Ok, excellent. Closing since this will eventually trickle down to stable.
